import {
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  FileUser,
  Files,
  FolderKanban,
  Home,
  Image as ImageIcon,
  KeyRound,
  Layers,
  LayoutDashboard,
  Mail,
  Menu,
  MessageCircleQuestion,
  Newspaper,
  Package,
  Palette,
  PanelBottom,
  Quote,
  Radar,
  Send,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Tags,
  UserCog,
  Users,
  type LucideIcon,
} from "lucide-react";

const ADMIN_ICONS: Record<string, LucideIcon> = {
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  FileUser,
  Files,
  FolderKanban,
  Home,
  Image: ImageIcon,
  KeyRound,
  Layers,
  LayoutDashboard,
  Mail,
  Menu,
  MessageCircleQuestion,
  Newspaper,
  Package,
  Palette,
  PanelBottom,
  Quote,
  Radar,
  Send,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Tags,
  UserCog,
  Users,
};

export function AdminIcon({ name, className }: { name: string; className?: string }) {
  const Component = ADMIN_ICONS[name] ?? LayoutDashboard;
  return <Component className={className} strokeWidth={1.7} aria-hidden="true" />;
}
